version: '3.8'
services:
  app:
    container_name: spotify-playing-feed
    build: .
    environment:
      NODE_ENV: production
      HOST: 0.0.0.0
      PORT: 3000
      SPOTIFY_REDIRECT_URI: http://localhost:3000/auth/callback
      SPOTIFY_CLIENT_ID: 6441a77da1fb4846869309f857837973
      SPOTIFY_CLIENT_SECRET: eff10b23163d496eb999fc3eba638015
      DISCORD_WEBOOK_URLS: https://discord.com/api/webhooks/865417598752260106/Hn1wfcldsTvYcYp4eciyNKHtzZSE-L0q2ujXvfrGED8rroNsRZbex2Qkaw8uAq7t0gpw
      MESSAGE_FORMAT: '%name% is playing %track_url% %scrapbox_link%'
      WATCH_INTERVAL_SECONDS: 60
    ports:
      - 3000:3000
    volumes:
      - ./data:/app/data
