version: '3.8'
services:
  spotify-playing-feed:
    image: iamtakagi/spotify-playing-feed
    environment:
      HOST: 0.0.0.0
      PORT: 3000
      BASE_URL: http://localhost:3000
      SPOTIFY_REDIRECT_URI: http://localhost:3000/auth/callback
      SPOTIFY_CLIENT_ID: xxx
      SPOTIFY_CLIENT_SECRET: xxx
      # カンマで区切ると複数追加できます
      DISCORD_WEBOOK_URLS: https://discord.com/api/webhooks/xxx/xxx
      # 監視する間隔秒数　(25秒以下にするとレートリミットを超過する可能性が高まります)
      WATCH_INTERVAL_SECONDS: 25
      # Embed で送信するフィールド
      SHARE_ON_TWITTER: 'true'
      SCRAPBOX_LINK: 'true'
      EMBED_IMAGE: 'true'
    ports:
      - 3000:3000
    volumes:
      - ./data:/app/data
    restart: always
